---
- name: Install AUR helpers and user to work with them through Ansible
  hosts: "*"

  tasks:
    - name: Create the `aura` user
      become: true
      ansible.builtin.user:
        system: true
        name: aura
        create_home: true
        group: wheel

    - name: Allow the 'aura' user to run 'sudo pacman' without a password
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aura
        mode: '0440'
        line: 'aura ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: true
        validate: 'visudo -cf %s'

    - name: Install 'paru'
      kewlfft.aur.aur:
        name: paru
        use: makepkg
        state: present
      become: true
      become_user: aura
