---
- name: Install Ansible and all required dependencies
  hosts: "*"

  tasks:
    - name: Update list of packages
      become: true
      community.general.pacman:
        update_cache: true

    - name: Install 'ansible'
      become: true
      community.general.pacman:
        name: ansible
        state: present

    - name: Install 'ansible-lint'
      become: true
      community.general.pacman:
        name: ansible-lint
        state: present

    - name: Install 'python-packaging'
      become: true
      community.general.pacman:
        name: python-packaging
        state: present

    - name: Ansible install 'kewlfft.aur'
      ansible.builtin.command:
        cmd: ansible-galaxy collection install kewlfft.aur
      changed_when: false

    - name: Ansible disable cowsay
      ansible.builtin.lineinfile:
        path: /etc/environment
        mode: '0644'
        line: 'ANSIBLE_NOCOWS=1'
        create: true
      become: true
