---
- name: Install Ansible and all required dependencies
  hosts: "*"

  tasks:
    - name: Install 'ansible'
      become: true
      community.general.pacman:
        update_cache: true
        name: ansible
        state: present

    - name: Install 'ansible-lint'
      become: true
      community.general.pacman:
        update_cache: true
        name: ansible-lint
        state: present

    - name: Install 'python-packaging'
      become: true
      community.general.pacman:
        update_cache: true
        name: python-packaging
        state: present

    - name: Ansible install 'kewlfft.aur'
      ansible.builtin.shell:
        cmd: ansible-galaxy collection install kewlfft.aur

