---
- name: Install additional apps
  hosts: "*"

  tasks:
    #############################################################
    # Install apps from Arch Repos
    #############################################################
    - name: Install additional apps
      community.general.pacman:
        name:
          - extra/syncthing
          - extra/earlyoom
        state: present
      become: true

    - name: Enable 'earlyoom' service
      ansible.builtin.systemd:
        name: earlyoom.service
        enabled: true
        state: started
        masked: false
      become: true

    #############################################################
    # Install apps from Arch Users repos
    #############################################################
    - name: Install packages from AUR
      kewlfft.aur.aur:
        use: paru
        name:
          - aur/syncthing-gtk
          - aur/foxglove-studio-bin
          - aur/steam-devices-git # Required by Flatpak Steam
          - aur/visual-studio-code-bin
          - aur/kirc
        state: present
      become_user: pkg
      become: true

    - name: Create hook for VSCode
      become: true
      ansible.builtin.blockinfile:
        path: /etc/pacman.d/hooks/vscode.hook
        mode: '0644'
        create: true
        state: present
        block: |
          [Trigger]
          Operation=Install
          Operation=Upgrade
          Type=Package
          Target=visual-studio-code-bin

          [Action]
          Description=Fix files associations after VSCode
          Depends=sed
          When=PostTransaction
          NeedsTargets
          Exec=/bin/sh -c 'sed -i "s/\(inode\/directory=\|text\/plain=\)code.desktop;\(.*\)/\1\2/g" /usr/share/applications/mimeinfo.cache; sed -i "s/text\/plain;inode\/directory;//g" /usr/share/applications/code.desktop'

    #############################################################
    # Enable flathub
    #############################################################
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system
      become: true
    #############################################################
    # Install flatpak apps
    #############################################################
    - name: Install Flatpak apps
      community.general.flatpak:
        name: 
          - org.gnome.Podcasts
          - org.keepassxc.KeePassXC
          - io.mpv.Mpv
          - org.telegram.desktop
          - com.valvesoftware.Steam
          - md.obsidian.Obsidian
          - org.kde.kdenlive
          - org.onlyoffice.desktopeditors
          - com.obsproject.Studio
          - org.gnome.gitlab.YaLTeR.Identity
          - fr.romainvigier.MetadataCleaner
          - io.gitlab.idevecore.Pomodoro
          - org.kde.krita
          - io.missioncenter.MissionCenter
        method: system
        remote: flathub
        state: present
      become: true

    #############################################################
    # Autostart apps
    #############################################################
    - name: Create user Autostart directory
      ansible.builtin.file:
        path: ~/.config/autostart/
        state: directory
        mode: '0755'

    - name: Syncthing GTK
      ansible.builtin.copy:
        remote_src: true
        src: /usr/share/applications/syncthing-gtk.desktop
        dest: ~/.config/autostart/syncthing-gtk.desktop
        mode: '0755'
