---
- name: Bluetooth
  hosts: "*"

  tasks:
    - name: Enable 'bluetooth' service started
      ansible.builtin.systemd:
        name: bluetooth.service
        enabled: true
        state: started
        masked: false
      become: true
