---
- name: Install my favorite CLI tools
  hosts: "*"

  become: true
  tasks:
  - name: Update list of packages
    community.general.pacman:
      update_cache: true

  - name: Remove cli tools
    community.general.pacman:
      name: 
        - nano
        - vim
        - vim-runtime
      state: absent

  - name: Add favorite cli tools
    community.general.pacman:
      name: 
        - mc
        - less
        - man-db
        - tldr
        - jq
        - fd
        - ncdu
        - dust
        - curl
        - tmux
        - wget
        - htop
        - git
        - zsh
        - neovim
        - bmon
        - eza
        - zoxide
        - bat
        - neofetch
        - pkgfile
        - mlocate
        - ripgrep-all
        - flatpak
        - wireguard-tools
        - rsync
        - pwgen
      state: present

  - name: Set 'neovim' as default editor
    ansible.builtin.lineinfile:
      path: /etc/environment
      mode: '0644'
      line: 'EDITOR=nvim'
      create: true
    become: true
