---
- name: Install Docker and my favorite tools for Docker
  hosts: "*"

  tasks:
    - name: Update list of packages
      community.general.pacman:
        update_cache: true
      become: true

    - name: Install 'docker'
      community.general.pacman:
        name: docker
        state: present
      become: true

    - name: Install 'docker-compose'
      community.general.pacman:
        name: docker-compose
        state: present
      become: true

    - name: Install 'docker-buildx'
      community.general.pacman:
        name: extra/docker-buildx
        state: present
      become: true

    - name: Install 'aur/python-rocker'
      kewlfft.aur.aur:
        name: aur/python-rocker
        use: paru
        state: present
      become: true
      become_user: aura

    # Required for 'python-rocker'.
    - name: Install 'extra/xorg-xauth'
      community.general.pacman:
        name: extra/xorg-xauth
        state: present
      become: true

    - name: Enable 'docker' service
      ansible.builtin.systemd:
        name: docker.service
        enabled: true
        state: started
        masked: false
      become: true

    - name: Install 'aur/nvidia-container-runtime'
      kewlfft.aur.aur:
        name: aur/nvidia-container-runtime
        use: paru
        state: present
      become: true
      become_user: aura

    - name: Create 'daemon.json' for docker.
      become: true
      ansible.builtin.blockinfile:
        path: /etc/docker/daemon.json
        mode: '0644'
        create: true
        state: present
        block: |
          {
            "runtimes": {
                "nvidia": {
                    "path": "/usr/bin/nvidia-container-runtime",
                    "runtimeArgs": []
                }
            },
            "default-ulimits": {
              "nofile": {
                  "Name": "nofile",
                  "Hard": 524288,
                  "Soft": 1024
              }
            }
          }

    - name: Get the 'username'
      ansible.builtin.shell:
        cmd: whoami
      changed_when: false
      register: running_as

    - name: Add the user '{{ running_as.stdout }}' to the docker groups
      ansible.builtin.user:
        name: "{{ running_as.stdout }}"
        groups: docker
        append: yes
      become: true
