---
- name: Install Docker and my favorite tools for Docker
  hosts: "*"

  tasks:
    - name: Update list of packages
      community.general.pacman:
        update_cache: true
      become: true

    - name: Install 'docker'
      community.general.pacman:
        name: docker
        state: present

    - name: Install 'docker-compose'
      community.general.pacman:
        name: docker-compose
        state: present

    - name: Install 'community/docker-buildx'
      community.general.pacman:
        name: extra/docker-buildx
        state: present

    - name: Install 'aur/python-rocker'
      kewlfft.aur.aur:
        name: aur/python-rocker
        use: paru
        state: present
      become: true
      become_user: aura

    - name: Enable 'docker' service
      ansible.builtin.systemd:
        name: docker.service
        enabled: true
        state: started
        masked: false
      become: true

    - name: Get the 'username'
      ansible.builtin.shell:
        cmd: whoami
      changed_when: false
      register: running_as

    - name: Add the user '{{ running_as.stdout }}' to the docker groups
      ansible.builtin.user:
        name: "{{ running_as.stdout }}"
        groups: docker
        append: yes
      become: true
