---
- name: Configure Gnome Look & Feel
  hosts: "*"

  tasks:
    - name: Update list of packages
      community.general.pacman:
        update_cache: true
      become: true

    #############################################################
    # Install dependencies
    #############################################################
    - name: Install dependencies
      community.general.pacman:
        name:
          - extra/python-psutil # required for community.general.dconf
        state: present
      become: true

    #############################################################
    # Clean gnome unused gnome packages after install
    #############################################################
    - name: Remove unused apps
      community.general.pacman:
        name:
          - gedit
          - epiphany
          - orca
          - rygel
          - totem
          - cheese
          - gnome-logs
          - gnome-music
          - gnome-photos
          - gnome-terminal
          - gnome-system-monitor
        state: absent
      become: true

    #############################################################
    # Install gnome packages
    #############################################################
    - name: Install additional apps
      community.general.pacman:
        name:
          - gnome-tweaks
          - extra/ffmpegthumbnailer
          - extra/gnome-text-editor
          - extra/gnome-console
          - extra/evince
          - extra/baobab
          - extra/eog
          - extra/file-roller
          - extra/dconf-editor
          - extra/webp-pixbuf-loader
          - extra/gnome-firmware
          - extra/gnome-control-center
        state: present
      become: true

    #############################################################
    # Install extensions
    #############################################################
    - name: Install base extensions
      community.general.pacman:
        name:
          - gnome-shell-extensions
          - gnome-shell-extension-appindicator
        state: present
      become: true

    - name: Install extensions from AUR
      kewlfft.aur.aur:
        use: paru
        name:
          - aur/gnome-shell-extension-blur-my-shell
          - aur/gnome-shell-extension-tiling-assistant
        state: present
      become_user: pkg
      become: true

    - name: Install Extension Manager
      community.general.flatpak:
        name: com.mattjakeman.ExtensionManager
        remote: flathub
        state: present
        method: system
      become: true

    #############################################################
    # Install themes, icons & fonts
    #############################################################
    - name: Install themes, icons & fonts
      community.general.pacman:
        name:
          - gnome-themes-extra
          - papirus-icon-theme
          - qt5ct
          - extra/noto-fonts
          - extra/noto-fonts-cjk
          - extra/noto-fonts-emoji
          - extra/noto-fonts-extra
          - extra/ttf-dejavu
          - extra/ttf-fira-code
          - extra/adobe-source-code-pro-fonts
          - extra/adobe-source-han-sans-jp-fonts
          - extra/adobe-source-han-serif-jp-fonts
        state: present
      become: true

    - name: Install additional themes
      kewlfft.aur.aur:
        use: paru
        name:
          - aur/adwaita-qt5-git
          - aur/adwaita-qt6-git
          - aur/gnome-shell-extension-blur-my-shell
          - aur/gnome-shell-extension-tiling-assistant
        state: present
      become_user: pkg
      become: true

    #############################################################
    # Configure look of KDE apps
    #############################################################
    - name: Add 'qt5ct' into '/etc/environment'
      ansible.builtin.lineinfile:
        path: /etc/environment
        mode: '0644'
        line: 'QT_QPA_PLATFORMTHEME=qt5ct'
        create: true
      become: true

    - name: Set default theme as 'Adwaita-Dark'
      ansible.builtin.lineinfile:
        path: /etc/environment
        mode: '0644'
        line: 'QT_STYLE_OVERRIDE=Adwaita-Dark'
        create: true
      become: true

    - name: Set platform theme as Gnome
      ansible.builtin.lineinfile:
        path: /etc/environment
        mode: '0644'
        line: 'QT_QPA_PLATFORMTHEME=gnome'
        create: true
      become: true

    - name: Disable Qt Auto Scaling
      ansible.builtin.lineinfile:
        path: /etc/environment
        mode: '0644'
        line: 'QT_AUTO_SCREEN_SCALE_FACTOR=0'
        create: true
      become: true

    - name: Set specific scaling for Qt
      ansible.builtin.lineinfile:
        path: /etc/environment
        mode: '0644'
        line: 'QT_SCALE_FACTOR=1.25'
        create: true
      become: true

    - name: Set QPA platform for Qt
      ansible.builtin.lineinfile:
        path: /etc/environment
        mode: '0644'
        line: 'QT_QPA_PLATFORM=wayland'
        create: true
      become: true

    #############################################################
    # Configure Gnome
    #############################################################
    - name: Enable gnome shell user extensions
      community.general.dconf:
        key: "/org/gnome/shell/disable-user-extensions"
        value: "false"
        state: present

    - name: Set list of enabled extensions
      community.general.dconf:
        key: "/org/gnome/shell/enabled-extensions"
        value: "['appindicatorsupport@rgcjonas.gmail.com', 'blur-my-shell@aunetx', 'places-menu@gnome-shell-extensions.gcampax.github.com', 'tiling-assistant@leleat-on-github', 'drive-menu@gnome-shell-extensions.gcampax.github.com']"
        state: present

    - name: Set windwos buttons 'minimize,maximize,close'
      community.general.dconf:
        key: "/org/gnome/desktop/wm/preferences/button-layout"
        value: "'appmenu:minimize,maximize,close'"
        state: present

    - name: Automatic suspend on AC power 'nothing'
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
        value: "'nothing'"
        state: present

    - name: Power button action 'suspend'
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/power/power-button-action"
        value: "'suspend'"
        state: present

    - name: Input sources 'en'
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/sources"
        value: "[('xkb', 'us')]"
        state: present

    - name: Set language per-window
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/per-window"
        value: "true"
        state: present

    - name: Interface color scheme 'prefer-dark'
      community.general.dconf:
        key: "/org/gnome/desktop/interface/color-scheme"
        value: "'prefer-dark'"
        state: present

    - name: Show weekday in shell clock
      community.general.dconf:
        key: "/org/gnome/desktop/interface/clock-show-weekday"
        value: "true"
        state: present

    - name: Show week number in Calendar
      community.general.dconf:
        key: "/org/gnome/desktop/calendar/show-weekdate"
        value: "true"
        state: present

    - name: Interface clock format '24h'
      community.general.dconf:
        key: "/org/gnome/desktop/interface/clock-format"
        value: "'24h'"
        state: present

    - name: Interface GTK theme 'Adwaita-dark'
      community.general.dconf:
        key: "/org/gnome/desktop/interface/gtk-theme"
        value: "'Adwaita-dark'"
        state: present

    - name: Interface icon theme 'Papirus-Dark'
      community.general.dconf:
        key: "/org/gnome/desktop/interface/icon-theme"
        value: "'Papirus-Dark'"
        state: present

    - name: Set font hinting to slight
      community.general.dconf:
        key: "/org/gnome/desktop/interface/font-hinting"
        value: "'slight'"
        state: present

    - name: Set font antialiasing to subpixel
      community.general.dconf:
        key: "/org/gnome/desktop/interface/font-antialiasing"
        value: "'rgba'"
        state: present

    - name: Nautilus show Size as first
      community.general.dconf:
        key: "/org/gnome/nautilus/icon-view/captions"
        value: "['size', 'none', 'none']"
        state: present

    - name: Set Favorite Apps
      community.general.dconf:
        key: "/org/gnome/shell/favorite-apps"
        value: "['code.desktop', 'org.mozilla.firefox.desktop', 'md.obsidian.Obsidian.desktop']"
        state: present

    - name: Remove system sounds
      community.general.dconf:
        key: "/org/gnome/desktop/sound/event-sounds"
        value: "false"
        state: present

    - name: Disable Hot Corner
      community.general.dconf:
        key: "/org/gnome/desktop/interface/enable-hot-corners"
        value: "false"
        state: present

    - name: Text Editor Show Line Numbers
      community.general.dconf:
        key: "/org/gnome/TextEditor/show-line-numbers"
        value: "true"
        state: present

    - name: Text Editor Highlight Current Line
      community.general.dconf:
        key: "/org/gnome/TextEditor/highlight-current-line"
        value: "true"
        state: present

    - name: Text Editor Show Map
      community.general.dconf:
        key: "/org/gnome/TextEditor/show-map"
        value: "true"
        state: present

    - name: Text Editor Indent Style
      community.general.dconf:
        key: "/org/gnome/TextEditor/indent-style"
        value: "'space'"
        state: present

    - name: Text Editor Indent Style
      community.general.dconf:
        key: "/org/gnome/TextEditor/tab-width"
        value: "4"
        state: present

    - name: Enable fractional scaling
      community.general.dconf:
        key: "/org/gnome/mutter/experimental-features"
        value: "['scale-monitor-framebuffer']"
        state: present

    #############################################################
    # Setting Wallpaper
    #############################################################
    - name: Create directory for Wallpapers
      ansible.builtin.file:
        path: /usr/share/backgrounds/custom
        state: directory
        mode: '0755'
      become: true

    - name: 'Download wallpaper #2'
      ansible.builtin.get_url:
        url: https://w.wallhaven.cc/full/lm/wallhaven-lmmo8r.jpg
        dest: /usr/share/backgrounds/custom/wallhaven-lmmo8r.jpg
        checksum: sha1:afb93ca794da2264d405ab3626cda467793248c4
        force: true
        mode: '0644'
      become: true

    - name: Set background picture
      community.general.dconf:
        key: '/org/gnome/desktop/background/picture-uri'
        value: "'file:///usr/share/backgrounds/custom/wallhaven-lmmo8r.jpg'"
        state: present

    - name: Set background picture (dark mode)
      community.general.dconf:
        key: '/org/gnome/desktop/background/picture-uri-dark'
        value: "'file:///usr/share/backgrounds/custom/wallhaven-lmmo8r.jpg'"
        state: present

    - name: Set screensaver picture
      community.general.dconf:
        key: '/org/gnome/desktop/background/picture-uri-dark'
        value: "'file:///usr/share/backgrounds/custom/wallhaven-lmmo8r.jpg'"
        state: present

    - name: Set background primary color
      community.general.dconf:
        key: '/org/gnome/desktop/background/primary-color'
        value: "'#000000000000'"
        state: present

    - name: Set background secondary color
      community.general.dconf:
        key: '/org/gnome/desktop/background/secondary-color'
        value: "'#000000000000'"
        state: present

    - name: Set screensaver primary color
      community.general.dconf:
        key: '/org/gnome/desktop/screensaver/primary-color'
        value: "'#000000000000'"
        state: present

    - name: Set screensaver secondary color
      community.general.dconf:
        key: '/org/gnome/desktop/screensaver/secondary-color'
        value: "'#000000000000'"
        state: present
