---
- name: Configure Gnome Look & Feel
  hosts: "*"

  tasks:
    - name: Update list of packages
      community.general.pacman:
        update_cache: true
      become: true

    #############################################################
    # Install dependencies
    #############################################################
    - name: Install dependencies
      community.general.pacman:
        name:
          - community/python-psutil # required for community.general.dconf
          - community/npm # required by 'aur/gnome-shell-extension-material-you-theme-git'
        state: present
      become: true

    #############################################################
    # Enable flathub
    #############################################################
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system
      become: true

    #############################################################
    # Clean gnome unused gnome packages after install
    #############################################################
    - name: Remove unused apps
      community.general.pacman:
        name:
          - gedit
          - epiphany
          - orca
          - rygel
          - totem
          - cheese
          - gnome-logs
          - gnome-music
          - gnome-photos
          - gnome-terminal
        state: absent
      become: true

    #############################################################
    # Install gnome packages
    #############################################################
    - name: Install additional apps
      community.general.pacman:
        name:
          - gnome-tweaks
          - extra/ffmpegthumbnailer
          - extra/gnome-text-editor
          - extra/gnome-console
          - extra/evince
          - extra/baobab
          - extra/eog
          - extra/file-roller
          - extra/dconf-editor
          - community/webp-pixbuf-loader
          - community/fwupd
          - community/fwupd-efi
          - community/gnome-firmware
        state: present
      become: true

    #############################################################
    # Install extensions
    #############################################################
    - name: Install base extensions
      community.general.pacman:
        name:
          - gnome-shell-extensions
          - gnome-shell-extension-appindicator
        state: present
      become: true

    - name: Install extensions from AUR
      kewlfft.aur.aur:
        use: trizen
        name:
          - aur/gnome-shell-extension-blur-my-shell
          - aur/gnome-shell-extension-tiling-assistant
          - aur/gnome-shell-extension-space-bar-git
        state: present
      become_user: aura
      become: true

    - name: Install Extension Manager
      community.general.flatpak:
        name: com.mattjakeman.ExtensionManager
        remote: flathub
        state: present
        method: system
      become: true

    #############################################################
    # Install themes, icons & fonts
    #############################################################
    - name: Install themes, icons & fonts
      community.general.pacman:
        name:
          - adwaita-qt5
          - adwaita-qt6
          - gnome-themes-extra
          - papirus-icon-theme
          - qt5ct
          - community/ttf-fira-code
        state: present
      become: true

    #############################################################
    # Configure look of KDE apps
    #############################################################
    - name: Add 'qt5ct' into '/etc/environment'
      ansible.builtin.lineinfile:
        path: /etc/environment
        mode: '0644'
        line: 'QT_QPA_PLATFORMTHEME=qt5ct'
        create: true
      become: true

    - name: Set default theme as 'Adwaita-Dark'
      ansible.builtin.lineinfile:
        path: /etc/environment
        mode: '0644'
        line: 'QT_STYLE_OVERRIDE=Adwaita-Dark'
        create: true
      become: true

    - name: Set platform theme as Gnome
      ansible.builtin.lineinfile:
        path: /etc/environment
        mode: '0644'
        line: 'QT_QPA_PLATFORMTHEME=gnome'
        create: true
      become: true

    #############################################################
    # Configure Gnome
    #############################################################
    - name: Enable gnome shell user extensions
      community.general.dconf:
        key: "/org/gnome/shell/disable-user-extensions"
        value: "false"
        state: present

    - name: Set list of enabled extensions
      community.general.dconf:
        key: "/org/gnome/shell/enabled-extensions"
        value: "['GPU_profile_selector@lorenzo9904.gmail.com', 'appindicatorsupport@rgcjonas.gmail.com', 'blur-my-shell@aunetx', 'places-menu@gnome-shell-extensions.gcampax.github.com', 'tiling-assistant@leleat-on-github', 'drive-menu@gnome-shell-extensions.gcampax.github.com', 'space-bar@luchrioh']"
        state: present

    - name: Set windwos buttons 'minimize,maximize,close'
      community.general.dconf:
        key: "/org/gnome/desktop/wm/preferences/button-layout"
        value: "'appmenu:minimize,maximize,close'"
        state: present

    - name: Automatic suspend on AC power 'nothing'
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
        value: "'nothing'"
        state: present

    - name: Power button action 'suspend'
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/power/power-button-action"
        value: "'suspend'"
        state: present

    - name: Input sources 'en,ru'
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/sources"
        value: "[('xkb', 'us'), ('xkb', 'ru')]"
        state: present

    - name: Switch input sources 'CapsLock'
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['grp:caps_toggle']"
        state: present

    - name: Set language per-window
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/per-window"
        value: "true"
        state: present

    - name: Interface color scheme 'prefer-dark'
      community.general.dconf:
        key: "/org/gnome/desktop/interface/color-scheme"
        value: "'prefer-dark'"
        state: present

    - name: Show weekday in shell clock
      community.general.dconf:
        key: "/org/gnome/desktop/interface/clock-show-weekday"
        value: "true"
        state: present

    - name: Show week number in Calendar
      community.general.dconf:
        key: "/org/gnome/desktop/calendar/show-weekdate"
        value: "true"
        state: present

    - name: Interface clock format '24h'
      community.general.dconf:
        key: "/org/gnome/desktop/interface/clock-format"
        value: "'24h'"
        state: present

    - name: Interface GTK theme 'Adwaita-dark'
      community.general.dconf:
        key: "/org/gnome/desktop/interface/gtk-theme"
        value: "'Adwaita-dark'"
        state: present

    - name: Interface icon theme 'Papirus-Dark'
      community.general.dconf:
        key: "/org/gnome/desktop/interface/icon-theme"
        value: "'Papirus-Dark'"
        state: present

    - name: Set font hinting to slight
      community.general.dconf:
        key: "/org/gnome/desktop/interface/font-hinting"
        value: "'slight'"
        state: present

    - name: Set font antialiasing to subpixel
      community.general.dconf:
        key: "/org/gnome/desktop/interface/font-antialiasing"
        value: "'rgba'"
        state: present

    - name: Nautilus show Size as first
      community.general.dconf:
        key: "/org/gnome/nautilus/icon-view/captions"
        value: "['size', 'none', 'none']"
        state: present

    - name: Remove system sounds
      community.general.dconf:
        key: "/org/gnome/desktop/sound/event-sounds"
        value: "false"
        state: present

    #############################################################
    # Setting Wallpaper
    #############################################################
    - name: Create directory for Wallpapers
      ansible.builtin.file:
        path: /usr/share/backgrounds/custom
        state: directory
        mode: '0755'
      become: true

    - name: 'Download wallpaper #1'
      ansible.builtin.get_url:
        url: https://w.wallhaven.cc/full/kw/wallhaven-kwwgx7.jpg
        dest: /usr/share/backgrounds/custom/wallhaven-kwwgx7.jpg
        checksum: sha1:de704a1acd0af436f31c8b1efd36846f38fd2b43
        force: true
        mode: '0644'
      become: true

    - name: 'Download wallpaper #2'
      ansible.builtin.get_url:
        url: https://w.wallhaven.cc/full/lm/wallhaven-lmmo8r.jpg
        dest: /usr/share/backgrounds/custom/wallhaven-lmmo8r.jpg
        checksum: sha1:afb93ca794da2264d405ab3626cda467793248c4
        force: true
        mode: '0644'
      become: true

    - name: 'Download wallpaper #3'
      ansible.builtin.get_url:
        url: https://w.wallhaven.cc/full/83/wallhaven-833w52.jpg
        dest: /usr/share/backgrounds/custom/wallhaven-833w52.jpg
        checksum: sha1:ebf01334d96dbb45be7269e9459698440a1965d3
        force: true
        mode: '0644'
      become: true

    - name: 'Download wallpaper #4'
      ansible.builtin.get_url:
        url: https://w.wallhaven.cc/full/9m/wallhaven-9mel2k.png
        dest: /usr/share/backgrounds/custom/wallhaven-9mel2k.jpg
        checksum: sha1:574dbf55af3e304e33527a6b3a5a899b68197864
        force: true
        mode: '0644'
      become: true

    - name: Set background picture
      community.general.dconf:
        key: '/org/gnome/desktop/background/picture-uri'
        value: "'file:///usr/share/backgrounds/custom/wallhaven-9mel2k.jpg'"
        state: present

    - name: Set background picture (dark mode)
      community.general.dconf:
        key: '/org/gnome/desktop/background/picture-uri-dark'
        value: "'file:///usr/share/backgrounds/custom/wallhaven-9mel2k.jpg'"
        state: present

    - name: Set screensaver picture
      community.general.dconf:
        key: '/org/gnome/desktop/background/picture-uri-dark'
        value: "'file:///usr/share/backgrounds/custom/wallhaven-9mel2k.jpg'"
        state: present

    - name: Set background primary color
      community.general.dconf:
        key: '/org/gnome/desktop/background/primary-color'
        value: "'#000000000000'"
        state: present

    - name: Set background secondary color
      community.general.dconf:
        key: '/org/gnome/desktop/background/secondary-color'
        value: "'#000000000000'"
        state: present

    - name: Set screensaver primary color
      community.general.dconf:
        key: '/org/gnome/desktop/screensaver/primary-color'
        value: "'#000000000000'"
        state: present

    - name: Set screensaver secondary color
      community.general.dconf:
        key: '/org/gnome/desktop/screensaver/secondary-color'
        value: "'#000000000000'"
        state: present
