---
- name: Configure Gnome Look & Feel
  hosts: "*"

  tasks:
    - name: Update list of packages
      community.general.pacman:
        update_cache: true
      become: true

    #############################################################
    # Install dependencies
    #############################################################
    - name: Install 'python-psutil'
      community.general.pacman:
        name: community/python-psutil # required for community.general.dconf
        state: present
      become: true

    #############################################################
    # Enable flathub
    #############################################################
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system
      become: true
    #############################################################
    # Clean gnome unused gnome packages after install
    #############################################################
    - name: Remove unused apps
      community.general.pacman:
        name:
          - gedit
          - epiphany
          - orca
          - rygel
          - totem
          - cheese
          - gnome-logs
          - gnome-music
          - gnome-photos
          - gnome-terminal
        state: absent
      become: true

    #############################################################
    # Install gnome packages
    #############################################################
    - name: Install additional apps
      community.general.pacman:
        name:
          - gnome-tweaks
          - extra/ffmpegthumbnailer
          - extra/gnome-text-editor
          - extra/gnome-console
          - extra/evince
          - extra/baobab
          - extra/eog
          - extra/file-roller
          - extra/dconf-editor
          - webp-pixbuf-loader
        state: present
      become: true

    #############################################################
    # Install extensions
    #############################################################
    - name: Install base extensions
      community.general.pacman:
        name:
          - gnome-shell-extensions
          - gnome-shell-extension-appindicator
        state: present
      become: true

    - name: Install Extension Manager
      community.general.flatpak:
        name: com.mattjakeman.ExtensionManager
        remote: flathub
        state: present
        method: system
      become: true

    #############################################################
    # Install themes & icons
    #############################################################
    - name: Install themes & icons
      community.general.pacman:
        name:
          - adwaita-qt5
          - adwaita-qt6
          - gnome-themes-extra
          - papirus-icon-theme
          - qt5ct
        state: present
      become: true

    #############################################################
    # Configure look of KDE apps
    #############################################################
    - name: Add 'qt5ct' into '/etc/environment'
      ansible.builtin.lineinfile:
        path: /etc/environment
        mode: 0644
        line: 'QT_QPA_PLATFORMTHEME=qt5ct'
        create: true
      become: true

    #############################################################
    # Configure Gnome
    #############################################################
    - name: Enable gnome shell user extensions
      community.general.dconf:
        key: "/org/gnome/shell/disable-user-extensions"
        value: "false"
        state: present

    - name: Set windwos buttons 'minimize,maximize,close'
      community.general.dconf:
        key: "/org/gnome/desktop/wm/preferences/button-layout"
        value: "'appmenu:minimize,maximize,close'"
        state: present

    - name: Automatic suspend on AC power 'nothing'
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
        value: "'nothing'"
        state: present

    - name: Power button action 'suspend'
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/power/power-button-action"
        value: "'suspend'"
        state: present

    - name: Input sources 'en,ru'
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/sources"
        value: "[('xkb', 'us'), ('xkb', 'ru')]"
        state: present

    - name: Switch input sources 'CapsLock'
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['grp:caps_toggle']"
        state: present

    - name: Set language per-window
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/per-window"
        value: "true"
        state: present

    - name: Interface color scheme 'prefer-dark'
      community.general.dconf:
        key: "/org/gnome/desktop/interface/color-scheme"
        value: "'prefer-dark'"
        state: present

    - name: Show weekday in shell clock
      community.general.dconf:
        key: "/org/gnome/desktop/interface/clock-show-weekday"
        value: "true"
        state: present

    - name: Show week number in Calendar
      community.general.dconf:
        key: "/org/gnome/desktop/calendar/show-weekdate"
        value: "true"
        state: present

    - name: Interface clock format '24h'
      community.general.dconf:
        key: "/org/gnome/desktop/interface/clock-format"
        value: "'24h'"
        state: present

    - name: Interface GTK theme 'Adwaita-dark'
      community.general.dconf:
        key: "/org/gnome/desktop/interface/gtk-theme"
        value: "'Adwaita-dark'"
        state: present

    - name: Interface icon theme 'Papirus-Dark'
      community.general.dconf:
        key: "/org/gnome/desktop/interface/icon-theme"
        value: "'Papirus-Dark'"
        state: present

    - name: Set font hinting to slight
      community.general.dconf:
        key: "/org/gnome/desktop/interface/font-hinting"
        value: "'slight'"
        state: present

    - name: Set font antialiasing to subpixel
      community.general.dconf:
        key: "/org/gnome/desktop/interface/font-antialiasing"
        value: "'rgba'"
        state: present
