---
- name: Configure Gnome Look & Feel
  hosts: "*"

  tasks:
  - name: Update list of packages
    community.general.pacman:
      update_cache: true
    become: true

  #############################################################
  # Clean gnome unused gnome packages after install
  #############################################################
  - name: Remove 'gedit'
    community.general.pacman:
      name: gedit
      state: absent
    become: true

  - name: Remove 'gnome-terminal'
    community.general.pacman:
      name: gnome-terminal
      state: absent
    become: true

  - name: Remove 'epiphany' # gnome browser
    community.general.pacman:
      name: epiphany
      state: absent
    become: true

  - name: Remove 'cheese'
    community.general.pacman:
      name: cheese
      state: absent
    become: true

  - name: Remove 'totem' # video player
    community.general.pacman:
      name: totem
      state: absent
    become: true

  #############################################################
  # Install extensions
  #############################################################
  - name: Install 'gnome-shell-extensions'
    community.general.pacman:
      name: gnome-shell-extensions
      state: present
    become: true

  - name: Install extension 'gnome-shell-extension-appindicator'
    community.general.pacman:
      name: gnome-shell-extension-appindicator
      state: present
    become: true

  #############################################################
  # Install reolacement for deleted packages
  #############################################################
  - name: Install from AUR 'gnome-text-editor'
    kewlfft.aur.aur:
      name: aur/gnome-text-editor
      use: trizen
      state: present
    become: true
    become_user: aura

  - name: Install from AUR 'gnome-console'
    kewlfft.aur.aur:
      name: aur/gnome-console
      use: trizen
      state: present
    become: true
    become_user: aura

  #############################################################
  # Install themes & icons
  #############################################################
  - name: Install 'adwaita-qt5'
    community.general.pacman:
      name: adwaita-qt5
      state: present
    become: true

  - name: Install 'adwaita-qt6'
    community.general.pacman:
      name: adwaita-qt6
      state: present
    become: true

  - name: Install 'gnome-themes-extra'
    community.general.pacman:
      name: gnome-themes-extra
      state: present
    become: true

  - name: Install 'papirus-icon-theme'
    community.general.pacman:
      name: papirus-icon-theme
      state: present
    become: true

  #############################################################
  # Install configuration tools for KDE apps
  #############################################################
  - name: Install 'qt5ct'
    community.general.pacman:
      name: qt5ct
      state: present
    become: true

  #############################################################
  # Configure look of KDE apps
  #############################################################
  - name: Add 'qt5ct' into '/etc/environment'
    ansible.builtin.lineinfile:
      path: /etc/environment
      mode: 0644
      line: 'QT_QPA_PLATFORMTHEME=qt5ct'
      create: true
    become: true

  #############################################################
  # Configure Gnome
  #############################################################
  - name: Set windwos buttons 'minimize,maximize,close'
    community.general.dconf:
      key: "/org/gnome/desktop/wm/preferences/button-layout"
      value: "'appmenu:minimize,maximize,close'"
      state: present

  - name: Automatic suspend on AC power 'nothing'
    community.general.dconf:
      key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
      value: "'nothing'"
      state: present

  - name: Power button action 'suspend'
    community.general.dconf:
      key: "/org/gnome/settings-daemon/plugins/power/power-button-action"
      value: "'suspend'"
      state: present

  - name: Input sources 'en,ru'
    community.general.dconf:
      key: "/org/gnome/desktop/input-sources/sources"
      value: "[('xkb', 'us'), ('xkb', 'ru')]"
      state: present

  - name: Switch input sources 'CapsLock'
    community.general.dconf:
      key: "/org/gnome/desktop/input-sources/xkb-options"
      value: "['grp:caps_toggle']"
      state: present

  - name: Input sources per-window 'true'
    community.general.dconf:
      key: "/org/gnome/desktop/input-sources/per-window"
      value: "true"
      state: present

  - name: Interface color scheme 'prefer-dark'
    community.general.dconf:
      key: "/org/gnome/desktop/interface/color-scheme"
      value: "'prefer-dark'"
      state: present

  - name: Interface clock show weekday 'true'
    community.general.dconf:
      key: "/org/gnome/desktop/interface/clock-show-weekday"
      value: "true"
      state: present

  - name: Interface week number 'true'
    community.general.dconf:
      key: "/org/gnome/desktop/calendar/show-weekdate"
      value: "true"
      state: present

  - name: Interface clock format '24h'
    community.general.dconf:
      key: "/org/gnome/desktop/interface/clock-format"
      value: "'24h'"
      state: present

  - name: Interface GTK theme 'Adwaita-dark'
    community.general.dconf:
      key: "/org/gnome/desktop/interface/gtk-theme"
      value: "'Adwaita-dark'"
      state: present

  - name: Interface icon theme 'Papirus-Dark'
    community.general.dconf:
      key: "/org/gnome/desktop/interface/icon-theme"
      value: "'Papirus-Dark'"
      state: present
