---
- name: Install Nvidia drivers & tools
  hosts: "*"

  tasks:
    - name: Update list of packages
      community.general.pacman:
        update_cache: true
      become: true

    - name: Install Nvidia
      community.general.pacman:
        name:
          - core/linux-headers
          - core/linux-lts-headers
          - extra/nvidia-dkms
          - extra/nvidia-utils
          - extra/nvidia-settings
          - extra/opencl-nvidia
          - extra/cuda
          - extra/nvtop
        state: present
      become: true

    # - name: GPU Profile Selector
    #   kewlfft.aur.aur:
    #     name:
    #       - aur/gnome-shell-extension-gpu-profile-selector-git
    #     use: paru
    #     state: present
    #   become_user: aura
    #   become: true
