---
- name: Install Tuxedo tools
  hosts: "*"

  tasks:
    - name: Update list of packages
      community.general.pacman:
        update_cache: true
      become: true

    - name: Install Tuxedo tools
      kewlfft.aur.aur:
        name:
          - aur/tuxedo-control-center-bin
          - aur/tuxedo-keyboard-dkms
          - aur/tuxedo-keyboard-tools
        use: trizen
        state: present
      become_user: aura
      become: true
